### ISSUE TITLE
Disclaimer for trackint in "Datenschutzerklärung"

### ISSUE THREAD

**Issue by FabianCernota** [FreifunkWesterwald/issues#19]
XXXX(Hier) kannst du dem tracking wiedersprechen. Link is missing

**Comment by justelex** [comment]
The link is not Usefull as long as we did not implement Piwik Tracking

**Comment by FabianCernota** [comment]
So long we should remove sentence.

**Comment by justelex** [comment]
Go for it. But we should ensure that it is in with if the tracking is included.

**Comment by MoritzKn** [comment]
Yet there is no tracking, so we can close this issues, right?

**Comment by FabianCernota** [comment]
No there will be piwik tracking soon

**Comment by FabianCernota** [comment]
Close
