### ISSUE TITLE
Search HTML entities shown

### ISSUE THREAD

**Issue by FabianCernota** [FreifunkWesterwald/issues#28]
![bug](https://cloud.githubusercontent.com/assets/9626021/13670025/aa818112-e6c7-11e5-83f5-d95cf9756fae.png)

**Comment by MoritzKn** [comment]
Was a bug in the gulp-hypher used for adding `&shy;`. I fixed it and created a pull request (bobwallis/gulp-hypher#1).

**Comment by MoritzKn** [comment]
PR is merged and gulp-hypher v1.0.3 contains the fix. Updated on the server. Works fine now.
