### ISSUE TITLE
Hyphenation not working on website

### ISSUE THREAD

**Issue by FabianCernota** [FreifunkWesterwald/issues#4]
Hyphens not working in Android Chrome and Desktop Chrome

Using http://mnater.github.io/Hyphenator/ will fix this.

**Comment by MoritzKn** [comment]
Den 'gulp-hypher' zur grunt build chain hinzugefügt, das fügt dann (wie auch der Hyphenator) `&shy;`'s ein.
Beim build der Seite muss nun nur `grunt gulp:hypher` nach Jekyll ausgeführt werden.
Grunt muss dafür installiert sein (`sudo npm install grunt-cli`).
