### ISSUE TITLE
Link der alten Seite umleiten.

### ISSUE THREAD

**Issue by NSASpecialist** [FreifunkWesterwald/issues#8]
***1 Upvote*** Bei dem Artikel der Altenkirchener Piraten auf Facebook ist die alte Seite verlinkt. 

freifunk-westerwald.de/doku.php

kann man das irgendwie auf die aktuelle Seite umleiten? Nicht das doch mal einer den Link von denen nutzt und auf einem "Not found" landet.

**Comment by FabianCernota** [comment]
+1

**Comment by FabianCernota** [comment]
Redirect activated with comment
